#!/bin/sh

set -e
set -x

if [ -z "$PGDATABASE" ] || [ -z "$PGUSER" ] || [ -z "$PGPASSWORD" ]; then
  echo "Please set variable PGDATABASE, PGUSER and PGPASSWORD"
  exit 2
fi 

CREATE_DATABASE=$PGDATABASE
CREATE_USER=$PGUSER
CREATE_PASSWORD=$PGPASSWORD
unset PGDATABASE PGUSER PGPASSWORD PGHOST PGPORT

# Create user
psql -c "CREATE ROLE $CREATE_USER WITH NOCREATEDB NOCREATEROLE NOCREATEUSER LOGIN" || true
psql -c "ALTER ROLE $CREATE_USER WITH PASSWORD '$CREATE_PASSWORD'"

# Create DB
dropdb "$CREATE_DATABASE" || true
createdb -O "$CREATE_USER" --encoding UNICODE "$CREATE_DATABASE" "OASIS-DB persistent data" || true
psql -c "GRANT ALL ON DATABASE $CREATE_DATABASE TO $CREATE_USER"

## Initialize DB
PGDATABASE=$CREATE_DATABASE
PGUSER=$CREATE_USER
PGPASSWORD=$CREATE_PASSWORD
PGHOST=localhost
export PGDATABASE PGUSER PGPASSWORD PGHOST
psql < $(dirname $0)/oasis-db.sql

